version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  data:
