version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: postgres/Dockerfile
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4:4.2
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    
volumes:
  data:
  pgadmin: